# Generated by Django 5.2.8 on 2026-04-07 13:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_stock'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='lineapedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_positiva_check'),
        ),
    ]
